# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

imp_neighbour_avg <- function(x, k) {
    .Call('_MsCoreUtils_imp_neighbour_avg', PACKAGE = 'MsCoreUtils', x, k)
}

